---# Config by Teunboeke

# Edit the message when the player executes the "/show" command.
command.show-player-message: "§aYou will now see players again." 

# Edit the message when the player executes the "/hide" command.
hide-player-message: "§cYou will no longer see players."

# Config by Teunboeke # Thanks for using my Plugin!...



